import {useEffect,useState} from 'react'
import {ArrowUpRight,BookOpen,Check,ChevronRight,ClipboardCheck,Download,ExternalLink,FileText,FolderOpen,Globe2,Info,Leaf,LoaderCircle,LockKeyhole,Plus,RefreshCw,Search,ShieldCheck,Trash2,Upload} from 'lucide-react'
import {api,post,downloadJSON} from './lib'
import type {Lang,Citation} from './lib'
import {t} from './i18n'
import type {Key} from './i18n'
import {Button} from './components/ui/button'
import {Dialog,DialogContent,DialogTitle,DialogDescription} from './components/ui/dialog'

type Shared={lang:Lang;user:any;onError:(e:unknown)=>void;onNotice:(v:string)=>void;onAuth:()=>void;onCitation:(c:Citation)=>void}
function Heading({title,sub,action}:{title:string;sub:string;action?:React.ReactNode}){return <div className="page-heading"><div><span className="eyebrow">IP-SAKTI SAHAYAK</span><h1>{title}</h1><p>{sub}</p></div>{action}</div>}
function Empty({text,children}:{text:string;children?:React.ReactNode}){return <div className="empty-state"><FolderOpen size={34} strokeWidth={1.2}/><h3>{text}</h3>{children}</div>}
function AuthGate({lang,onAuth}:Shared){return <Empty text={t('needAccount',lang)}><Button onClick={onAuth}>{t('signIn',lang)}</Button></Empty>}
function CiteList({citations,lang,onCitation}:{citations:Citation[];lang:Lang;onCitation:(c:Citation)=>void}){return <div className="source-chips">{citations.map((c,i)=><button onClick={()=>onCitation(c)} key={c.id}><span>{i+1}</span><div><strong>{c.title}</strong><small>{c.locator.slice(0,100)}</small></div><ArrowUpRight size={16}/></button>)}</div>}

export function AssessmentPage(props:Shared&{kind:'classification'|'abs'}){
 const {lang,kind,onError,onCitation}=props,tr=(k:Key)=>t(k,lang)
 const [state,setState]=useState<any>(null),[busy,setBusy]=useState(false)
 async function step(answers:Record<string,string>={},id=state?.assessment_id){setBusy(true);try{setState(await post('/assessments/'+kind,{assessment_id:id,answers,language:lang}))}catch(e){onError(e)}finally{setBusy(false)}}
 useEffect(()=>{void step({},null)},[])
 return <section className="content-page assessment-page"><Heading title={tr(kind)} sub={tr(kind==='abs'?'absSub':'classificationSub')} action={<Button variant="outline" onClick={()=>step({},null)}><RefreshCw size={15}/>{tr('restart')}</Button>}/>
  <p className="badge neutral">{tr('india')}</p>
  {!state&&<div className="loading-answer"><LoaderCircle className="spin"/>{tr('working')}</div>}
  {state&&!state.complete&&<div className="assessment-card"><div className="assessment-progress"><span>{tr('question')} {state.answered+1}</span><span className="rule-version">{state.rule_version}</span></div><div className="progress-track"><span style={{width:Math.min(95,(state.answered+1)*13)+'%'}}/></div><h2>{state.question.text}</h2><div className="option-list">{state.question.options.map((o:any)=><button key={o.value} disabled={busy} onClick={()=>step({[state.question.id]:o.value})}><span className="option-radio"/>{o.label}<ChevronRight size={18}/></button>)}</div><p className="muted"><ShieldCheck size={15}/>{tr('provisional')}</p></div>}
  {state?.complete&&<div className="assessment-result"><div className="result-banner"><span className="small-emblem"><Check size={22}/></span><div><span className="eyebrow">{tr('provisional')}</span><h2>{state.title}</h2></div><Button variant="outline" size="sm" onClick={()=>downloadJSON('ipsakti-'+kind+'.json',state)}><Download size={15}/>{tr('export')}</Button></div>
    <div className="result-body">{state.posture&&Object.entries(state.posture).map(([k,v])=><div className="posture-row" key={k}><h3>{tr(({regulatory:'regulatory',ip:'ip',traditional_knowledge:'tk',abs:'abs'} as Record<string,Key>)[k])}</h3><p>{String(v)}</p></div>)}{state.checklist&&<ol className="checklist">{state.checklist.map((item:string)=><li key={item}>{item}</li>)}</ol>}<div className="info-box"><Info size={18}/><div><strong>{tr('authority')}</strong><p>{state.authority_to_consult}</p></div></div>{state.missing_facts.length>0&&<p><strong>{tr('missing')}: </strong>{state.missing_facts.join(', ')}</p>}<h3>{tr('citations')}</h3><CiteList citations={state.citations} lang={lang} onCitation={onCitation}/>{!state.citations.length&&<p className="muted">{tr('insufficient')}</p>}<ul className="muted-list">{state.limitations.map((l:string)=><li key={l}>{l}</li>)}</ul><p className="source-language">{tr('sourceLanguage')}</p></div></div>}
 </section>
}

export function LibraryPage(props:Shared&{coverage:any}){
 const {lang,coverage,onError,onCitation}=props,tr=(k:Key)=>t(k,lang)
 const [sources,setSources]=useState<any[]>([]),[query,setQuery]=useState(''),[scope,setScope]=useState('all'),[searchResult,setSearchResult]=useState<any>(null),[busy,setBusy]=useState(false)
 useEffect(()=>{api<any[]>('/sources').then(setSources).catch(onError)},[])
 const filtered=sources.filter(s=>(scope==='all'||s.jurisdiction===scope)&&(s.title+' '+s.category+' '+s.publisher).toLowerCase().includes(query.toLowerCase()))
 async function fullSearch(){if(query.length<2)return;setBusy(true);try{setSearchResult(await api('/sources/search?'+new URLSearchParams({query,jurisdiction:scope==='international'?'international':'india'})))}catch(e){onError(e)}finally{setBusy(false)}}
 return <section className="content-page"><Heading title={tr('sources')} sub={tr('librarySub')}/><div className="metrics-strip">{[['sourceCount',coverage?.sources],['downloaded',coverage?.versions],['approved',coverage?.approved_versions]].map(([k,v])=><div key={String(k)}><strong>{v??'—'}</strong><span>{tr(k as Key)}</span></div>)}<div className="metrics-note"><ShieldCheck size={21}/><span>{coverage?.release?.name||tr('insufficient')}</span></div></div>
  <div className="filter-bar"><label className="search-field"><Search size={18}/><input value={query} onChange={e=>{setQuery(e.target.value);setSearchResult(null)}} placeholder={tr('searchSources')} aria-label={tr('searchSources')}/></label><select aria-label="Jurisdiction filter" value={scope} onChange={e=>setScope(e.target.value)}>{(['all','india','international'] as const).map(v=><option value={v} key={v}>{tr(v)}</option>)}</select><Button variant="outline" onClick={fullSearch} disabled={busy||query.length<2}>{tr('search')}</Button></div>
  {searchResult&&<div className="search-results"><h3>{tr('retrieval')}</h3><CiteList citations={searchResult.citations} lang={lang} onCitation={onCitation}/>{!searchResult.citations.length&&<p>{tr('noResults')}</p>}</div>}
  <div className="source-table-wrap"><table className="source-table"><thead><tr><th>{tr('sources')}</th><th>{tr('reviewStatus')}</th><th>{tr('snapshot')}</th><th/></tr></thead><tbody>{filtered.map(s=><tr key={s.id}><td><div className="table-title"><BookOpen size={19}/><div><strong>{s.title}</strong><span>{s.publisher} · {s.jurisdiction} / {s.market} · {s.authority}</span></div></div><p className="source-note">{s.notes}</p></td><td><span className={`badge ${s.versions[0]?.review_status==='approved'?'green':s.versions.length?'amber':'neutral'}`}>{s.versions[0]?.review_status||s.disposition}</span></td><td>{s.versions[0]?<a className="text-link" href={'/api/v1/sources/versions/'+s.versions[0].id+'/file'} target="_blank" rel="noreferrer"><Download size={16}/>{new Date(s.versions[0].retrieved_at).toLocaleDateString()}</a>:<span className="muted">—</span>}</td><td><a className="icon-link" href={s.url} target="_blank" rel="noreferrer" aria-label={tr('official')}><ExternalLink size={17}/></a></td></tr>)}</tbody></table>{!filtered.length&&<Empty text={tr('noResults')}/>}</div>
  <details className="coverage-details"><summary>{tr('coverage')}</summary><div className="coverage-grid">{Object.entries(coverage?.categories||{}).map(([key,value])=><div key={key}><strong>{key.replaceAll(':',' / ')}</strong><small>{(value as any).downloaded}/{(value as any).sources} acquired · {(value as any).approved} approved</small></div>)}</div></details>
 </section>
}

export function CasesPage(props:Shared&{onOpenCase:(c:any)=>void}){
 const {lang,user,onError,onNotice}=props,tr=(k:Key)=>t(k,lang)
 const [cases,setCases]=useState<any[]>([]),[selected,setSelected]=useState<any>(null),[review,setReview]=useState(false),[summary,setSummary]=useState(''),[includeHistory,setIncludeHistory]=useState(false),[permission,setPermission]=useState(false),[documents,setDocuments]=useState<any[]>([]),[remove,setRemove]=useState(false),[newCase,setNewCase]=useState(false),[title,setTitle]=useState('')
 async function load(){try{setCases(await api('/cases'))}catch(e){onError(e)}}
 useEffect(()=>{if(user)void load()},[user])
 useEffect(()=>{if(selected)api<any[]>('/cases/'+selected.id+'/documents').then(setDocuments).catch(onError)},[selected?.id])
 async function create(e:React.FormEvent){e.preventDefault();try{const c=await post('/cases',{title,jurisdiction:'india',confidential:true});setNewCase(false);setTitle('');setSelected(c);await load()}catch(e){onError(e)}}
 async function upload(file:File){if(!permission){onError(tr('permission'));return}const form=new FormData();form.append('file',file);form.append('permission','true');try{await api('/cases/'+selected.id+'/documents',{method:'POST',body:form});setDocuments(await api('/cases/'+selected.id+'/documents'));onNotice(tr('saved'))}catch(e){onError(e)}}
 async function sendReview(){try{await post('/cases/'+selected.id+'/review',{summary,include_history:includeHistory});setReview(false);setSummary('');onNotice(tr('submitted'))}catch(e){onError(e)}}
 async function deleteCase(){try{await api('/cases/'+selected.id,{method:'DELETE'});setSelected(null);setRemove(false);await load();onNotice(tr('saved'))}catch(e){onError(e)}}
 if(!user)return <section className="content-page"><Heading title={tr('cases')} sub={tr('casesSub')}/><AuthGate {...props}/></section>
 return <section className="content-page"><Heading title={tr('cases')} sub={tr('casesSub')} action={<Button onClick={()=>setNewCase(true)}><Plus size={17}/>{tr('save')}</Button>}/>{!cases.length?<Empty text={tr('emptyCases')}/>:<div className="case-layout"><div className="case-list">{cases.map(c=><button key={c.id} className={selected?.id===c.id?'selected':''} onClick={()=>setSelected(c)}><FolderOpen size={21}/><div><strong>{c.title}</strong><small>{c.jurisdiction} · {new Date(c.updated_at).toLocaleDateString()}</small></div><ChevronRight size={15}/></button>)}</div><div className="case-detail">{selected?<><div className="case-title"><span className="badge green"><LockKeyhole size={12}/>{tr('confidential')}</span><h2>{selected.title}</h2><span className="muted">{selected.jurisdiction} / {selected.market}</span></div><div className="button-row"><Button size="sm" onClick={()=>props.onOpenCase(selected)}>{tr('assistant')}<ChevronRight size={14}/></Button><Button variant="outline" size="sm" onClick={()=>downloadJSON('ipsakti-case.json',selected)}><Download size={14}/>JSON</Button><Button variant="outline" size="sm" asChild><a href={'/api/v1/cases/'+selected.id+'/export?format=pdf'} target="_blank" rel="noreferrer"><Download size={14}/>PDF</a></Button><Button size="sm" onClick={()=>setReview(true)}><ClipboardCheck size={14}/>{tr('requestReview')}</Button><Button size="icon" variant="ghost" aria-label={tr('delete')} onClick={()=>setRemove(true)}><Trash2 size={16}/></Button></div><div className="saved-history">{selected.content.history?.map((turn:any,i:number)=><details key={i}><summary>{turn.question}</summary>{turn.answer.claims?.map((c:any,j:number)=><p key={j}>{c.text}</p>)}<CiteList citations={turn.answer.citations||[]} lang={lang} onCitation={props.onCitation}/></details>)}</div><div className="private-upload"><h3><Upload size={18}/>{tr('upload')}</h3><p>{tr('privateNote')}</p><label className="checkbox-label"><input type="checkbox" checked={permission} onChange={e=>setPermission(e.target.checked)}/>{tr('permission')}</label><input type="file" aria-label={tr('upload')} accept=".pdf,.txt" disabled={!permission} onChange={e=>{const f=e.target.files?.[0];if(f)void upload(f);e.target.value=''}}/>{documents.map(d=><div key={d.id} className="document-item"><FileText size={16}/>{d.name}<small>{d.characters.toLocaleString()} characters</small></div>)}</div></>:<Empty text={tr('cases')}/>}</div></div>}
  <Dialog open={review} onOpenChange={setReview}><DialogContent><DialogTitle>{tr('requestReview')}</DialogTitle><DialogDescription>{tr('reviewSub')}</DialogDescription><div className="stack-form"><label>{tr('shareSummary')}<textarea value={summary} onChange={e=>setSummary(e.target.value)} minLength={10} maxLength={10000}/></label><label className="checkbox-label"><input type="checkbox" checked={includeHistory} onChange={e=>setIncludeHistory(e.target.checked)}/>{tr('includeHistory')}</label><Button disabled={summary.trim().length<10} onClick={sendReview}>{tr('requestReview')}</Button></div></DialogContent></Dialog>
  <Dialog open={remove} onOpenChange={setRemove}><DialogContent><DialogTitle>{tr('delete')}</DialogTitle><DialogDescription>{tr('confirmDelete')}</DialogDescription><div className="button-row"><Button variant="outline" onClick={()=>setRemove(false)}>{tr('cancel')}</Button><Button variant="destructive" onClick={deleteCase}>{tr('delete')}</Button></div></DialogContent></Dialog>
  <Dialog open={newCase} onOpenChange={setNewCase}><DialogContent><DialogTitle>{tr('save')}</DialogTitle><DialogDescription>{tr('casesSub')}</DialogDescription><form className="stack-form" onSubmit={create}><label>{tr('title')}<input required maxLength={180} value={title} onChange={e=>setTitle(e.target.value)}/></label><Button>{tr('save')}</Button></form></DialogContent></Dialog>
 </section>
}

export function ReviewPage(props:Shared){
 const {lang,user,onError,onNotice}=props,tr=(k:Key)=>t(k,lang)
 const [items,setItems]=useState<any[]>([]),[responses,setResponses]=useState<Record<string,string>>({})
 async function load(){try{setItems(await api('/reviews'))}catch(e){onError(e)}}
 useEffect(()=>{if(user)void load()},[user])
 async function advance(id:string,status:string){try{await api('/reviews/'+id,{method:'PATCH',body:JSON.stringify({status,response:responses[id]||''})});await load();onNotice(tr('saved'))}catch(e){onError(e)}}
 return <section className="content-page"><Heading title={tr('reviews')} sub={tr('reviewSub')}/>{!user?<AuthGate {...props}/>:!items.length?<Empty text={tr('noResults')}/>:<div className="review-list">{items.map(item=><article className="review-card" key={item.id}><div className="button-row"><span className="badge amber">{item.status}</span>{!item.assigned_to&&<small className="muted">{tr('submitted')}</small>}</div><h2>{item.shared_content.title}</h2><p>{item.shared_content.summary}</p><small>{item.shared_content.jurisdiction} / {item.shared_content.market}</small>{item.shared_content.history?.length>0&&<details><summary>{tr('includeHistory')}</summary>{item.shared_content.history.map((h:any,i:number)=><div key={i}><h4>{h.question}</h4>{h.answer?.claims?.map((c:any,j:number)=><p key={j}>{c.text}</p>)}</div>)}</details>}{item.response&&<div className="info-box"><ClipboardCheck size={18}/><div><strong>{tr('reviewResponse')}</strong><p>{item.response}</p></div></div>}{['facilitator','admin'].includes(user.role)&&item.status!=='resolved'&&<div className="stack-form">{item.status==='in_review'&&<label>{tr('reviewResponse')}<textarea value={responses[item.id]||''} onChange={e=>setResponses({...responses,[item.id]:e.target.value})}/></label>}<Button onClick={()=>advance(item.id,{submitted:'assigned',assigned:'in_review',in_review:'resolved'}[item.status as 'submitted'])}>{tr(({submitted:'assign',assigned:'beginReview',in_review:'resolve'} as Record<string,Key>)[item.status])}</Button></div>}</article>)}</div>}</section>
}

export function PriorPage(props:Shared){
 const {lang,onError}=props,tr=(k:Key)=>t(k,lang)
 const [term,setTerm]=useState(''),[result,setResult]=useState<any>(null)
 async function submit(e:React.FormEvent){e.preventDefault();try{setResult(await api('/prior-art?term='+encodeURIComponent(term)))}catch(e){onError(e)}}
 return <section className="content-page narrow-page"><Heading title={tr('prior')} sub={tr('priorSub')}/><form className="search-panel" onSubmit={submit}><label>{tr('ingredient')}<input value={term} onChange={e=>setTerm(e.target.value)} placeholder="e.g. Ashwagandha" minLength={2} maxLength={150}/></label><Button disabled={term.length<2}><Search size={16}/>{tr('search')}</Button></form>{result&&<div className="prior-results"><h3>{tr('searchTerms')}</h3><div className="tag-list">{result.terms.map((term:string)=><span className="badge green" key={term}>{term}</span>)}</div><h3>{tr('queries')}</h3>{result.queries.map((query:string)=><pre key={query}>{query}</pre>)}<div className="registry-links">{result.links.map((link:any)=><a href={link.url} target="_blank" rel="noreferrer" key={link.url}><Globe2 size={20}/><strong>{link.title}</strong><ExternalLink size={17}/></a>)}</div><ul className="muted-list">{result.limitations.map((l:string)=><li key={l}>{l}</li>)}</ul></div>}</section>
}

export function SettingsPage(props:Shared&{caps:any;onDeleted:()=>void}){
 const {lang,user,caps,onError,onNotice,onDeleted}=props,tr=(k:Key)=>t(k,lang)
 const [consents,setConsents]=useState<any[]>([]),[provider,setProvider]=useState(''),[purpose,setPurpose]=useState(''),[remove,setRemove]=useState(false)
 async function load(){if(user)try{setConsents(await api('/consents'))}catch(e){onError(e)}}
 useEffect(()=>{void load()},[user])
 async function grant(e:React.FormEvent){e.preventDefault();try{await post('/consents',{provider,scope:'search',purpose,days:30});await load();setProvider('');setPurpose('');onNotice(tr('saved'))}catch(e){onError(e)}}
 async function revoke(id:string){try{await api('/consents/'+id,{method:'DELETE'});await load();onNotice(tr('revoked'))}catch(e){onError(e)}}
 async function deleteAccount(){try{await api('/account',{method:'DELETE'});setRemove(false);onDeleted()}catch(e){onError(e)}}
 return <section className="content-page settings-page"><Heading title={tr('settings')} sub={tr('settingsSub')}/><div className="settings-grid"><section className="settings-section"><h2>{tr('integrations')}</h2>{[['AI',caps?.generation?.provider,caps?.generation?.configured],['Bhashini','EN / HI / MR',caps?.bhashini?.configured],['Embeddings',caps?.embeddings?.model,caps?.embeddings?.enabled]].map(([name,detail,active])=><div className="integration-row" key={String(name)}><div><strong>{name}</strong><p>{detail||'—'}</p></div><span className={`badge ${active?'green':'neutral'}`}>{tr(active?'configured':'notConfigured')}</span></div>)}<p className="muted">{tr('noPaid')}</p></section><section className="settings-section"><h2>{tr('retention')}</h2><p>{tr('retentionText')}</p><p className="muted">{tr('cloudNote')}</p>{user&&<div className="button-row"><Button variant="outline" onClick={()=>api('/account/export').then(data=>downloadJSON('ipsakti-my-data.json',data)).catch(onError)}><Download size={15}/>{tr('exportAccount')}</Button><Button variant="ghost" onClick={()=>setRemove(true)}><Trash2 size={15}/>{tr('deleteAccount')}</Button></div>}</section></div><section className="settings-section consent-section"><h2>{tr('consent')}</h2><p className="muted">{tr('noPaid')}</p>{user?<><form className="consent-form" onSubmit={grant}><label>{tr('provider')}<input value={provider} onChange={e=>setProvider(e.target.value)} required maxLength={80}/></label><label>{tr('purpose')}<input value={purpose} onChange={e=>setPurpose(e.target.value)} required minLength={10} maxLength={500}/></label><Button>{tr('grant')}</Button></form>{consents.map(c=><div key={c.id} className="consent-row"><div><strong>{c.provider}</strong><p>{c.scope} · {c.purpose}</p><small>{new Date(c.expires_at).toLocaleDateString()}</small></div>{c.revoked?<span className="badge neutral">{tr('revoked')}</span>:<Button variant="outline" size="sm" onClick={()=>revoke(c.id)}>{tr('revoke')}</Button>}</div>)}</>:<Button variant="outline" onClick={props.onAuth}>{tr('signIn')}</Button>}</section><Dialog open={remove} onOpenChange={setRemove}><DialogContent><DialogTitle>{tr('deleteAccount')}</DialogTitle><DialogDescription>{tr('accountDeleteConfirm')}</DialogDescription><div className="button-row"><Button variant="outline" onClick={()=>setRemove(false)}>{tr('cancel')}</Button><Button variant="destructive" onClick={deleteAccount}>{tr('deleteAccount')}</Button></div></DialogContent></Dialog></section>
}

export function AdminPage(props:Shared&{onRefresh:()=>void}){
 const {lang,user,onError,onNotice,onRefresh}=props,tr=(k:Key)=>t(k,lang)
 const [sources,setSources]=useState<any[]>([]),[jobs,setJobs]=useState<any[]>([]),[releases,setReleases]=useState<any[]>([]),[graph,setGraph]=useState<any[]>([]),[selected,setSelected]=useState(''),[note,setNote]=useState(''),[releaseName,setReleaseName]=useState(''),[versions,setVersions]=useState<string[]>([])
 async function load(){try{const [s,j,r,g]=await Promise.all([api<any[]>('/sources'),api<any[]>('/admin/jobs'),api<any[]>('/admin/releases'),api<any[]>('/graph')]);setSources(s);setJobs(j);setReleases(r);setGraph(g);onRefresh()}catch(e){onError(e)}}
 useEffect(()=>{if(user&&['admin','curator'].includes(user.role))void load()},[user])
 async function enqueue(source_id:string){try{await post('/admin/jobs',{kind:'ingest',source_id});await load();onNotice(tr('saved'))}catch(e){onError(e)}}
 async function review(status:string){if(!selected)return;try{await api('/admin/versions/'+selected,{method:'PATCH',body:JSON.stringify({status,note})});await load();setNote('');onNotice(tr('saved'))}catch(e){onError(e)}}
 async function createRelease(){try{await post('/admin/releases',{name:releaseName,version_ids:versions,review_note:note});await load();onNotice(tr('saved'))}catch(e){onError(e)}}
 async function activate(id:string){try{await post('/admin/releases/'+id+'/activate',{});await load();onNotice(tr('saved'))}catch(e){onError(e)}}
 if(!user||!['admin','curator'].includes(user.role))return <section className="content-page"><AuthGate {...props}/></section>
 return <section className="content-page"><Heading title={tr('admin')} sub={tr('adminSub')} action={<Button variant="outline" onClick={load}><RefreshCw size={16}/>{tr('enqueue')}</Button>}/><div className="admin-columns"><section className="settings-section"><h2>{tr('reviewStatus')}</h2><div className="stack-form"><select aria-label="Source version" value={selected} onChange={e=>setSelected(e.target.value)}><option value="">{tr('sources')}</option>{sources.flatMap(s=>s.versions.map((v:any)=><option value={v.id} key={v.id}>{s.title} · {v.review_status}</option>))}</select><label>{tr('reviewNote')}<textarea value={note} onChange={e=>setNote(e.target.value)} minLength={30}/></label><div className="button-row"><Button onClick={()=>review('approved')} disabled={!selected||note.length<30}>{tr('approve')}</Button><Button variant="outline" onClick={()=>review('reference_only')} disabled={!selected||note.length<30}>{tr('reference')}</Button></div></div></section><section className="settings-section"><h2>{tr('jobs')}</h2><select aria-label="Source to update" defaultValue="" onChange={e=>{if(e.target.value)void enqueue(e.target.value);e.target.value=''}}><option value="">{tr('enqueue')}…</option>{sources.filter(s=>s.access==='public').map(s=><option key={s.id} value={s.id}>{s.title}</option>)}</select><div className="job-list">{jobs.slice(0,12).map(j=><div key={j.id}><strong>{j.kind} / {j.payload.source_id}</strong><span className="badge neutral">{j.status}</span>{j.result.error&&<p>{j.result.error}: {j.result.message}</p>}</div>)}</div></section></div>
  <section className="settings-section"><h2>{tr('releases')}</h2><div className="release-list">{releases.map(r=><div key={r.id}><strong>{r.name}</strong><small>{r.version_ids.length} versions</small>{r.active?<span className="badge green">Active</span>:<Button size="sm" variant="outline" onClick={()=>activate(r.id)}>{tr('activate')}</Button>}</div>)}</div><details><summary><Plus size={16}/>Create reviewed release</summary><div className="stack-form"><input aria-label="Release name" placeholder="Release name" value={releaseName} onChange={e=>setReleaseName(e.target.value)}/><div className="version-list">{sources.flatMap(s=>s.versions.filter((v:any)=>['reference_only','approved'].includes(v.review_status)).map((v:any)=><label className="checkbox-label" key={v.id}><input type="checkbox" checked={versions.includes(v.id)} onChange={e=>setVersions(e.target.checked?[...versions,v.id]:versions.filter(x=>x!==v.id))}/>{s.title} · {v.review_status}</label>))}</div><p className="muted">Uses the review note above. Select one version per source.</p><Button disabled={!versions.length||releaseName.length<3||note.length<30} onClick={createRelease}>Create release</Button></div></details></section>
  <section className="settings-section"><h2>{tr('graph')}</h2>{!graph.length?<p className="muted">No reviewed relationships in the active release.</p>:<div className="graph-table">{graph.map(e=><div key={e.id}><strong>{e.subject}</strong><span>{e.predicate}</span><strong>{e.object}</strong><button className="text-link" onClick={()=>api<Citation>('/sources/chunks/'+e.evidence_chunk_id).then(props.onCitation).catch(onError)}>{tr('viewSource')}<ArrowUpRight size={15}/></button></div>)}</div>}</section>
 </section>
}
